import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Desafio Lacrei</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/logo.png" />
      </Head>
      <HomeContainer></HomeContainer>
    </>
  );
}
